name: VotivePlayerSpeed
version: '${project.version}'
main: me.lorendel.votiveplayerspeed.VotivePlayerSpeed
api-version: 1.17
authors: [ Lorendel ]
description: Plugin created for the Votive Project
website: https://votiverp.com
commands:
  walk:
    description: Замедляет ходьбу персонажа.
  normalSpeed:
    description: Устанавливает обычную скорость персонажу.
  speedmenu:
    description: Открывает меню для настройки скорости